---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: "yes"
    cache_valid_time: "{{ debian_cache_valid_time }}"
  when: debian_cache_update | bool

- name: Install curl
  ansible.builtin.apt:
    pkg: curl
    state: present

- name: Install python-pycurl
  ansible.builtin.apt:
    pkg: "{{ python_package }}-pycurl"
    state: present

- name: Add backports repository
  ansible.builtin.apt_repository:
    repo: "deb http://{{ debian_repo_url }}/debian {{ debian_codename }}-backports main"
    state: present
    update_cache: "no"

- name: Add backports source repository
  ansible.builtin.apt_repository:
    repo: "deb-src http://{{ debian_repo_url }}/debian {{ debian_codename }}-backports main"
    state: present
    update_cache: "yes"

- name: Install python-configparser
  ansible.builtin.apt:
    pkg: python-configparser
    state: present
  when: "python_package == 'python'"

- name: Install python3-configparser
  ansible.builtin.apt:
    pkg: python3-configargparse
    state: present
  when: "python_package == 'python3'"

- name: Write inputrc
  ansible.builtin.copy:
    src: inputrc
    dest: /etc/inputrc
    owner: root
    group: root
    mode: "0644"
